# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('creation_date', models.DateField()),
                ('location', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('minute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('date', models.DateTimeField(null=True)),
                ('number_of_queue', models.IntegerField()),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='main.Club')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host', to='main.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Member_of_game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('since', models.IntegerField()),
                ('to', models.IntegerField()),
                ('games', models.ManyToManyField(to='main.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=45)),
                ('surname', models.CharField(max_length=45)),
                ('date_of_birth', models.DateField()),
                ('club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Club')),
            ],
        ),
        migrations.CreateModel(
            name='Persons_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('start', models.DateField()),
                ('end', models.DateField(null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Roles_in_game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(max_length=45, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategorys_of_work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('subcategory', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('quota', models.FloatField(null=True)),
                ('date', models.DateField()),
                ('new_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_club', to='main.Club')),
                ('old_club', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_club', to='main.Club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Types_of_event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=45, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types_of_work',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(max_length=45, null=True, unique=True)),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Subcategorys_of_work')),
            ],
        ),
        migrations.AddField(
            model_name='persons_history',
            name='type_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Types_of_work'),
        ),
        migrations.AddField(
            model_name='member_of_game',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
        migrations.AddField(
            model_name='member_of_game',
            name='roles',
            field=models.ManyToManyField(to='main.Roles_in_game'),
        ),
        migrations.AddField(
            model_name='event',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Game'),
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Person'),
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Types_of_event'),
        ),
    ]
